#!/bin/sh -e

# Will store the built package's files to
# allow us to cherry-pick the ICU related files.
mkdir -p tmp
export DESTDIR="$PWD/tmp"

meson \
    --prefix=/usr \
    -Dglib=enabled \
    -Dicu=enabled \
    -Dicu_builtin=false \
    -Dbenchmark=disabled \
    -Dcairo=disabled \
    -Ddocs=disabled \
    -Dtests=disabled \
    . output

ninja -C output
ninja -C output install

mkdir -p \
	"$1/usr/lib/pkgconfig" \
	"$1/usr/include/harfbuzz"

cp ./tmp/usr/lib/libharfbuzz-icu* "$1/usr/lib/"
cp ./tmp/usr/lib/pkgconfig/harfbuzz-icu.pc "$1/usr/lib/pkgconfig/"

cp ./tmp/usr/include/harfbuzz/hb-icu.h "$1/usr/include/harfbuzz/"
