#!/bin/sh -e

# remove unneeded utils
sed -e '/lsmod/d' \
	-e '/eject/d' \
	-e '/freeramdisk/d' \
	-e '/fsfreeze/d' \
	-e '/vtallow/d' \
	-e '/vmstat/d' \
	-e '/swaplabel/d' \
	-e '/rmmod/d' \
	-e '/insmod/d' \
	-e '/unshare/d' \
	-e '/lastlog/d' \
	Makefile > _
mv -f _ Makefile

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" PREFIX=/usr install

# su needs setuid to work properly
chmod 4755 "$1/usr/bin/su"
