#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dtls_check=false \
    -Dvapi=disabled \
    -Dgssapi=disabled \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Dbrotli=disabled \
    -Dsysprof=disabled \
    -Ddefault_libary=static \
    -Dgnome=false \
    . output

ninja -C output
ninja -C output install
