#!/bin/sh -e

./configure \
    --prefix=/usr \
    --datadir=/usr/share/openssh \
    --sysconfdir=/etc/ssh \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/openssh \
    --without-selinux \
    --with-privsep-user=nobody \
    --with-mantype=doc \
    --without-zlib-version-check \
    --without-rpath \
    --disable-strip \
    --with-ssl-engine \
    --with-pid-dir=/run \
    --disable-wtmp \
    --disable-utmp \
    --with-ldflags=-static

make 
make DESTDIR="$1" install

cp -f contrib/ssh-copy-id   "$1/usr/bin"
cp -f contrib/ssh-copy-id.1 "$1/usr/share/man/man1"
chmod +x "$1/usr/bin/ssh-copy-id"

# Install service file
mkdir -p "$1/etc/rcsm/avail"
cp -f sshd.run "$1/etc/rcsm/avail/sshd"
