#!/usr/bin/sh -e

cd linux
make 
make install

mkdir -p "$1/etc/spectrwm"
cp ../spectrwm.conf "$1/etc/spectrwm/"
cp ../spectrwm_us.conf "$1/etc/spectrwm/"

mkdir -p "$1/usr/bin/"
cp spectrwm "$1/usr/bin/"

mkdir -p "$1/usr/share/man/man1"
cp ../spectrwm.1 "$1/usr/share/man/man1"
