#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

# tar and strings is provided elsewhere.
# also remove other unneeded utilities
sed -e '/strings\\/d' \
	-e '/tar\\/d' \
	-e '/sha224sum\\/d' \
	-e '/sha384sum\\/d' \
	-e '/sha512-224sum\\/d' \
	-e '/sha512-256sum\\/d' \
	Makefile > _
mv -f _ Makefile

make LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -fPIE"
make DESTDIR="$1" PREFIX=/usr install

# for some reason these manpages still got included.
for p in strings tar sha224sum sha384sum sha512-224sum sha512-256sum; do
	rm -r "$1/usr/share/man/man1/$p.1"
done

# Install is installed as xinstall
mv -f "$1/usr/bin/xinstall" "$1/usr/bin/install"
mv -f "$1/usr/share/man/man1/xinstall.1" "$1/usr/share/man/man1/install.1"

