#!/bin/sh -e

# Set -Ddefault_library=both by default.
sed "/value: /s/'static'/'both'/" src/script/per_project_options.meson > _
mv -f _ src/script/per_project_options.meson

# workaround static build
sed '/MUON_STATIC/d' meson.build > _
mv -f _ meson.build

command -v muon > /dev/null || {
      ./bootstrap.sh build
    export PATH=$PWD/build:$PATH
    
}

muon setup \
      -Dprefix=/usr \
      -Ddocs=disabled \
      -Dlibcurl=disabled \
      -Dlibpkgconf=enabled \
      -Dstatic=true \
      -Dbestline=disabled \
      build

ninja -C build
muon  -C build install
