#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-shared \
    --without-exampled \
    --without-tests 

make LDFLAGS="$LDFLAGS --static"
make DESTDIR="$1" install

mkdir -p "$1/usr/lib/"
ln -s libexpat.a "$1/usr/lib/libexpat.so.1"
