#!/bin/sh -e

patch -p1 < surf-websearch-20190510-d068a38.diff
patch -p1 < surf-quit_hotkey-20210830-11dca18.diff
patch -p1 < modal.patch

# Kiss seems to bork surf's scrolling keybindings when using PREFIX=/usr
# This seems to fix the issue, while still install to /usr
sed 's|/usr/local|/usr|' config.mk > _
mv -f _ config.mk

make
make install
