#!/bin/sh 

patch -p1 < uselessgaps.patch

sed -i 's/PANEL_HEIGHT.*18/PANEL_HEIGHT 0/' config.def.h
sed -i 's/USELESSGAP.*8/USELESSGAP 10/' config.def.h

make LDFLAGS="$LDFLAGS --static -lX11 -lxcb -lXau"
make install
