#!/bin/sh -e

make
make install

install -Dm644 sysmgr.boot         "$1/etc/rc.d/sysmgr.boot"
install -Dm644 sysmgr.pre.shutdown "$1/usr/lib/init/rc.d/sysmgr.pre.shutdown"
install -Dm755 respawn             "$1/usr/bin/respawn"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/sm.license"
