#!/bin/sh -e

export DESTDIR="$1"

# we have to skip bad for now, so we can enable hls
for plugin in libav good ugly; do (
    cd "$plugin"

    meson \
        --prefix=/usr \
        -Dtests=disabled \
        . output

    ninja -C output
    ninja -C output install
) done

# build bad manually to enable hls
cd bad

meson \
    --prefix=/usr \
    -Dtests=disabled \
    -Dhls=enabled \
    . output

    ninja -C output
    ninja -C output install
