#!/bin/sh -e

export DESTDIR="$1"

# we have to skip bad for now, so we can enable hls
for plugin in libav good ugly bad; do (
    cd "$plugin"

	meson setup \
		-Dprefix=/usr \
		-Dbuildtype=release \
		-Ddoc=disabled \
		-Dtests=disabled \
		-Db_colorout=never \
		output

    ninja -C output
    ninja -C output install
) done
