#!/bin/sh -e

export DESTDIR="$1"

for plugin in libav good ugly; do (
    cd "$plugin"

	meson setup \
		-Dprefix=/usr \
		-Dbuildtype=release \
		-Ddoc=disabled \
		-Dtests=disabled \
		-Db_colorout=never \
		output

    ninja -C output
    ninja -C output install
) done

cd bad

	meson setup \
		-Dprefix=/usr \
		-Dbuildtype=release \
		-Ddoc=disabled \
		-Dtests=disabled \
		-Db_colorout=never \
		-Dtranscode=enabled \
		output

    ninja -C output
    ninja -C output install
