#!/bin/sh -e

patch -p1 < libressl-support.patch
patch -p1 < python3-always-pip.patch
patch -p1 < python3-pyc-hash.patch

# Remove util-linux dependency among other things.
cat >> Modules/Setup <<EOF
*disabled*
_uuid nis ossaudiodev
EOF

# Reported 20-27% performance improvements.
# See: "PythonNoSemanticInterpositionSpeedup"
export CFLAGS="$CFLAGS -fno-semantic-interposition"
export LDFLAGS="$LDFLAGS -fno-semantic-interposition"

./configure \
    --prefix=/usr \
    --enable-shared \
    --with-system-expat \
    --with-system-ffi \
    --with-ensurepip=yes \
    --without-doc-strings \
    --without-pymalloc \
    --with-builtin-hashlib-hashes="sha3,blake2,sha1,sha512,sha256,md5" \
    --with-ssl-default-suites="TLSv1.3:TLSv1.2+AEAD+ECDHE:TLSv1.2+AEAD+DHE"

make EXTRA_CFLAGS="$CFLAGS -DTHREAD_STACK_SIZE=0x100000"
make install

ln -s python3 "$1/usr/bin/python"
ln -s pip3    "$1/usr/bin/pip"

# Let's make some kind of effort to reduce the overall
# size of Python by removing a bunch of rarely used and
# otherwise useless components.
#
# This can't be done via ./configure as the build system
# doesn't give you this much control over the process.
{
    cd "$1/usr/lib/python"*
    rm -rf test ./*/test ./*/tests
    rm -rf pydoc* idlelib turtle* config-*

    cd "$1/usr/bin"
    rm -f pydoc* idle*
}
