#!/bin/sh -e

mkdir -p "$1/boot"

patch -p1 < no-perl.patch
patch -p1 < make-yacc-usage-POSIX-compliant.diff
#patch -p1 < amdgpufb.patch
patch -p1 < bash.patch

make

cp arch/x86/boot/bzImage "$1/boot/kiss.efi"
