#!/bin/sh -e

./configure \
	PROG_LDADD=-all-static \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-tests

make
make DESTDIR="$1" install

# certs now belongs to cacert
rm -rf "$1/etc/ssl"
