#!/bin/sh -e

# force static flag
sed 's/LDFLAGS =/LDFLAGS = -s -static/' Makefile > _
mv -f _ Makefile

# make sure its installed into /usr 
sed 's|/usr/local|/usr|' Makefile > _
mv -f _ Makefile

make figlet 
make DESTDIR="$1" install
