#!/bin/sh -e

patch -p1 < pax.patch

# fix orphan exclusion list
sed -e 's/baseinit/rcinit/' \
	-e 's/busybox/awk sbase ubase otools/' \
	-e 's/grub/libressl oksh/' \
	contrib/kiss-orphans > _
	mv -f _ contrib/kiss-orphans
	chmod 755 contrib/kiss-orphans

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/doc/kiss"

cp -f  kiss contrib/*  "$1/usr/bin"
cp -f  docs/site/*.txt "$1/usr/share/doc/kiss"
cp -rf docs/site/wiki  "$1/usr/share/doc/kiss"

rm -f \
    "$1/usr/share/doc/kiss/README.txt" \
    "$1/usr/share/doc/kiss/post.txt" \
    "$1/usr/share/doc/kiss/tidbits.txt"
