#!/bin/sh -e

patch -p1 < pax.patch

# fix orphan exclusion list
sed -e 's/baseinit/awk b3sum/' \
	-e 's/busybox/sbase ubase/' \
	-e 's/bzip2/otools libressl/' \
	-e 's/grub/rfinit/' \
	> _; mv -f _ contrib/kiss-orphans

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/doc/kiss"

cp -f  kiss contrib/*  "$1/usr/bin"
cp -f  docs/site/*.txt "$1/usr/share/doc/kiss"
cp -rf docs/site/wiki  "$1/usr/share/doc/kiss"

rm -f \
    "$1/usr/share/doc/kiss/README.txt" \
    "$1/usr/share/doc/kiss/post.txt" \
    "$1/usr/share/doc/kiss/tidbits.txt"
