#!/bin/sh -e

cat <<EOF

NOTE: A menu system has to be installed. Possible choices:

- fzf
- bemenu (external menu)

To use an external menu, see

	man 5 ytfzf

and the example of conf.sh in the package.


Optional: to view thumbnails, you have to install a 
thumbnail viewer. A list is available at

https://github.com/pystardust/ytfzf#alternative-thumbnail-viewers

NOTE: if mpv fails to play the video, it needs to be
rebuilt. 

EOF
