#!/bin/sh -e

# vendor libwm, as its not needed elsewhere at all
cd libwm

make
make PREFIX=/usr install

cd ..

# use super key, instead of alt key
sed 's/XCB_MOD_MASK_1/XCB_MOD_MASK_4/' config.def.h > _
mv -f _ config.def.h

# glazier complains about wm.h is missing in the dir
cp libwm/wm.h .

make 
make install

# libwm's files is no longer needed
rm -rf \
	"$1/usr/lib/libwm.a" \
	"$1/usr/include/wm.h"
