#!/bin/sh -e

# vendor libwm, as its not needed elsewhere at all
(
cd libwm

export CFLAGS="$CFLAGS -I/."
export LDFLAGS="$LDFLAGS -L/."

make
)

# fix compiler flags not being respected
sed -e 's/CFLAGS =/CFLAGS +=/' \
	-e 's/LDFLAGS =/LDFLAGS +=/' config.mk > _
mv -f _ config.mk

make 
make PREFIX=/usr install

# install manpage
mkdir -p "$1/usr/share/man/man1"
cp glazier.1 "$1/usr/share/man/man1"
