#!/bin/sh -e

export CFLAGS="$CFLAGS -DSMALL"

./configure \
    --prefix=/usr \
    --enable-sh \
    --enable-ksh \
    --enable-lto \
    --no-thanks \
    --enable-static

make
make DESTDIR="$1" install
