#!/bin/sh -e

export CFLAGS="$CFLAGS -DSMALL -fPIE"
export LDFLAGS="$LDFLAGS -static-pie"

./configure \
    --prefix=/usr \
    --enable-sh \
    --enable-ksh \
    --enable-lto \
    --no-thanks \
    --enable-small

make
make DESTDIR="$1" install
