#!/bin/sh -e

patch -p1 < keyrelease-hidetabs.patch

# using LDFLAGS seems to complain about some libs is missing when trying to
# statically link tabbed.
sed 's/-lX11/-lX11 -lxcb -lXau --static/' config.mk > _
mv -f _ config.mk

make  
make PREFIX=/usr install
