#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

patch -p1 < pkcs7-fix.patch

make \
    prefix="/usr" \
    DESTDIR="$1" \
    USE_SYSTEM_LIBS="yes" \
    HAVE_X11=yes \
    HAVE_WAYLAND=no \
    HAVE_GLUT=no \
    install

mv -f "$1/usr/bin/mupdf-x11" "$1/usr/bin/mupdf"
