#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

./configure \
    --prefix=/usr \
    --disable-alsa

make LDFLAGS="$LDFLAGS -ltinyalsa"
make install

mkdir -p                           "$1/etc/sv/sndiod"
cp -f sndiod.run                   "$1/etc/sv/sndiod/run"
ln -sf /run/runit/supervise.sndiod "$1/etc/sv/sndiod/supervise" 
