#!/bin/sh -e

# Only build libuuid 
./configure \
    --build=x86_64-unknown-linux-musl \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --disable-all-programs \
    --disable-rpath \
    --disable-shared \
    --enable-libuuid \
    --enable-libblkid \
    --without-udev \
    --without-python \
    --without-systemd \
    --without-ncursesw \
    --without-ncurses

make
make DESTDIR="$1" install

make clean
./configure \
    --build=x86_64-unknown-linux-musl \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --disable-shared \
    --disable-rpath \
    --without-udev \
    --without-python \
    --without-systemd \
    --without-ncursesw \
    --without-ncurses

make fdisk LDFLAGS="$LDFLAGS --static" 
make lsblk LDFLAGS="$LDFLAGS --static" 

chmod 755 fdisk lsblk
cp -f fdisk lsblk "$1/usr/bin"
cp -f disk-utils/fdisk.8 "$1/usr/share/man/man8"
cp -f misc-utils/lsblk.8 "$1/usr/share/man/man8"

rm -rf \
    "$1/usr/sbin" \
    "$1/usr/share/doc" \
    "$1/usr/share/bash-completion"
