#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-libuuid \
    --enable-libblkid \
    --disable-fsck \
    --disable-mount \
    --disable-sulogin \
    --disable-su \
    --disable-kill \
    --disable-rfkill \
    --disable-minix \
    --disable-bfs \
    --disable-cramfs \
    --disable-swapon \
    --disable-makeinstall-chown \
    --disable-rpath \
    --disable-pg-bell \
    --without-udev \
    --without-python \
    --without-ncursesw \
    --without-ncurses \
    --without-systemd

make
make install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

rm -rf \
    "$1/usr/share/doc" \
    "$1/usr/share/bash-completion"

