#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIE"
export LDFLAGS="$LDFLAGS -static-pie"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-shared

make bin_PROGRAMS=pkgconf 
make bin_PROGRAMS=pkgconf  DESTDIR="$1" install

ln -s pkgconf "$1/usr/bin/pkg-config"

# Remove documentation (README, etc).
rm -rf "$1/usr/share/doc"
