#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

for p in *.patch; do
    patch -p1 < "$p"
done

./configure \
    --include_dir=/usr/include

# remove dependency on libelf, among other things
for var in HAVE_ELF TC_CONFIG_XT; do
		sed "/$var/d" config.mk > _
		echo "$var := n" >> _
		mv -f _ config.mk
done
sed 's/DHAVE_ELF//' config.mk > _
mv -f _ config.mk
sed '/LDLIBS/d' config.mk > _
mv -f _ config.mk

make DESTDIR="$1" YACC=yacc

mkdir -p \
	"$1/usr/bin" \
	"$1/usr/share/man/man8"

for bin in ip bridge; do
	chmod 755 "$bin"/"$bin"
	cp -f "$bin"/"$bin" "$1/usr/bin"
	cp -f man/man8/"$bin".8 "$1/usr/share/man/man8"
done
