#!/bin/sh -e

meson \
    --prefix=/usr \
    -Dx11=enabled \
    -Dmanpage-build=enabled \
    -Degl=disabled \
    -Degl-x11=disabled \
    -Dgl=disabled \
    -Ddrm=disabled \
    -Dgbm=disabled \
    -Dstdatomic=disabled \
    . build

ninja -C build
ninja -C build install

# we probably dont need these
rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/icons"
