#!/bin/sh -e

# Setup docutils to generate manual pages.
{
    cd docutils

    python3 setup.py build
    python3 setup.py install \
        --root="$PWD/../dist"

    cd ../dist/usr/lib/python*/site-packages

    PYTHONPATH=$PWD:$(python -c "import sys;print(':'.join(sys.path))")

    cd -; cd ..
    export PATH=$PWD/dist/usr/bin:$PATH
    export PYTHONPATH
}

meson \
    --prefix=/usr \
    -Dx11=enabled \
    -Dmanpage-build=enabled \
    -Degl=disabled \
    -Degl-x11=disabled \
    -Dgl=disabled \
    -Ddrm=disabled \
    -Dalsa=disabled \
    . build

ninja -C build
ninja -C build install

# we probably dont need these
rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/icons"
