#!/bin/sh -e

export LDFLAGS="$LDFLAGS -lXrandr -lXrender -static"

muon setup \
    -Dprefix=/usr \
    -Dx11=enabled \
    -Dmanpage-build=enabled \
    -Degl=disabled \
    -Degl-x11=disabled \
    -Dgl=disabled \
    -Ddrm=disabled \
    -Dgbm=disabled \
    -Dalsa=enabled \
    -Dsndio=enabled \
    build

# to avoid having to build only static libs for alot of stuff,
# we force the use of static libs instead
sed 's/\.so/\.a/g' build/build.ninja > _
mv -f _ build/build.ninja
sed 's/libatomic.a.1.2.0/libatomic.a/g' build/build.ninja > _
mv -f _ build/build.ninja
sed 's/libXrender.a.1.3.0/libXrender.a/' build/build.ninja > _
mv -f _ build/build.ninja

ninja -C build
muon -C build install

# we probably dont need these
rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/icons"
