#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

make CFLAGS="$CFLAGS -fPIE" LDFLAGS="$LDFLAGS -static-pie"
make DESTDIR="$1" PREFIX=/usr install

mkdir -p "$1/etc/rcsm/avail"
cp -f sdhcp.run "$1/etc/rcsm/avail/sdhcp"
