#!/bin/sh -e

mkdir -p "$1/usr/bin/"
mkdir -p "$1/usr/share/man/man1"

make LDFLAGS=-static
cp sdhcp "$1/usr/bin/"
cp sdhcp.1 "$1/usr/share/man/man1"

mkdir -p "$1/etc/sv/sdhcp"
cp run "$1/etc/sv/sdhcp"
