#!/bin/sh -e


make CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS -static"

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/man/man1" \
    "$1/etc/sv/sdhcp"

cp -f sdhcp "$1/usr/bin"
cp -f sdhcp.1 "$1/usr/share/man/man1"

mkdir -p "$1/etc/rcsm/avail"
cp -f sdhcp.run "$1/etc/rcsm/avail/sdhcp"
