#!/bin/sh -e

for p in patch/*.patch; do
    patch -p1 < "$p"
done

# Remove forced gcc/g++ usage so builds work on gcc-less systems.
sed -e "s#= g[c+][c+]#= $CC#g" \
    -e "s#\(\$(CROSS_COMPILE)\)gcc#\1$CC#g" Makefile > _
mv -f _ Makefile

# Build and install regular busybox.
# This excludes utilities which require 'suid' to function.
make HOSTCC="$CC"
make CONFIG_PREFIX="$1/usr" install

# Install the symlinks.
"$1/usr/bin/busybox" --list | while read -r bin; do
    ln -s busybox "$1/usr/bin/$bin"
done
