#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIE"
export LDFLAGS="$LDFLAGS -static-pie"

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH="$PATH:$PWD"

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man

make
make DESTDIR="$1" install
