#!/bin/sh -e

export DESTDIR="$1"

# avoid bison
patch -p1 < byacc.patch
sed '/^args/{s/yfile,//;s/cfile/cfile, yfile/;}' gst/parse/gen_grammar.py.in > _
mv -f _ gst/parse/gen_grammar.py.in

meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Dbuildtype=release \
    -Ddbghelp=disabled \
    -Dintrospection=disabled \
    -Dexamples=disabled \
    -Ddoc=disabled \
    -Db_colorout=never \
    -Dtests=disabled \
    output

ninja -C output
ninja -C output install
