#!/bin/sh -e

CFLAGS="$CFLAGS --static"

#patch -p1 < POSIX.patch

./scripts/make.sh
PREFIX="$1/usr/bin" ./scripts/install.sh --symlink --force

chmod gu+s "$1/usr/bin/toybox"

# add init hooks swapon/swapoff
mkdir -p "$1/etc/rc.d"
cp swapon.boot swapoff.shutdown "$1/etc/rc.d"
