#!/bin/sh -e

./configure \
	--prefix=/usr \
	--with-system-zlib

make pax LDFLAGS="$LDFLAGS -static"

mkdir -p \
	"$1/usr/bin" \
	"$1/usr/share/man/man1"

cp -f pax "$1/usr/bin"

# symlink to tar and cpio
ln -s pax "$1/usr/bin/tar"
ln -s pax "$1/usr/bin/cpio"

cp -f bin/pax/pax.1 "$1/usr/share/man/man1"
cp -f bin/pax/tar.1 "$1/usr/share/man/man1"
cp -f bin/pax/cpio.1 "$1/usr/share/man/man1"
