#!/bin/sh -e

./configure \
    --prefix=/usr

make less LDFLAGS="$LDFLAGS -static"

# Only install less
mkdir -p \
       "$1/usr/bin" \
       "$1/usr/share/man/man1"

cp -f less "$1/usr/bin"
cp -f less.nro "$1/usr/share/man/man1/less.1"
