#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

# LFLAGS is used instead of LDFLAGS in Makefile
make \
	LFLAGS="$LDFLAGS -static-pie" \
	CFLAGS="$CFLAGS -fPIE -DPREFIX=\//usr -D_XOPEN_SOURCE=500" \
	PROMPT=null

mkdir -p \
       "$1/usr/bin" \
       "$1/usr/lib" \
       "$1/usr/share/man/man1"

chmod 755 rc
chmod 655 rcmain.unix rc.1

cp -f rc          "$1/usr/bin"
cp -f rcmain.unix "$1/usr/lib/rcmain"