#!/bin/sh -e

export DESTDIR="$1"

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH="$PATH:$PWD"

./configure \
    --prefix=/usr \
    --with-lib-path=/usr/lib \
    --enable-targets=x86_64-pep \
    --enable-deterministic-archives \
    --enable-ld=default \
    --enable-plugins \
    --enable-relro \
    --disable-lto \
    --disable-multilib \
    --disable-werror \
    --disable-gdb \
    --disable-nls \
    --disable-readline \
    --disable-gprof \
    --disable-gprofng \
    --without-zstd \
    --with-mmap \
    --with-pic \
    --with-system-zlib

make configure-host
make tooldir=/usr LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -fPIE"
make tooldir=/usr install

ln -sf ld.bfd "$1/usr/bin/ld"
