#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-static \
    --disable-shared \
    --disable-tiff \
    --enable-libwebpmux \
    --enable-libwebpdemux \
    --enable-libwebpdecoder

make
make install
