#!/bin/sh -e

make \
	HOSTCC=cc \
	CFLAGS="$CFLAGS $LDFLAGS -static-pie -fPIE" \
	YACC='yacc -d -b awkgram'

# Makefile doesnt have a install option
mkdir -p \
  "$1/usr/bin/" \
  "$1/usr/share/man/man1"

cp a.out "$1/usr/bin/awk"
cp awk.1 "$1/usr/share/man/man1"
