#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIE"
export LDFLAGS="$LDFLAGS -static-pie"

for p in *.patch; do
	patch -p1 < "$p"
done

mkdir -p \
  "$1/usr/bin/" \
  "$1/usr/share/man/man1"

make

# Makefile doesnt have a install option
cp a.out "$1/usr/bin/awk"
cp awk.1 "$1/usr/share/man/man1"
