#!/bin/sh -e

./configure \
	--prefix=/usr \
	--without-selinux \
	--disable-shared \
	--without-blkid

make LDFLAGS="$LDFLAGS --static"
make install

# install binaries to bin instead
mv -f "$1/usr/sbin" "$1/usr/bin"

rm -rf \
	"$1/usr/lib" \
	"$1/usr/include"
