#!/bin/sh -ef

make CFLAGS="$CFLAGS -fPIE" LDFLAGS="$LDFLAGS -static-pie"

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/man/man1"

cp  -f pigz   "$1/usr/bin"
ln -sf pigz   "$1/usr/bin/gzip"
cp  -f pigz.1 "$1/usr/share/man/man1"
ln -sf pigz.1 "$1/usr/share/man/man1/gzip.1"
