#!/bin/sh -e

export LDFLAGS="$LDFLAGS -Wl,--gc-sections"
export CFLAGS="$CFLAGS -ffunction-sections -fdata-sections"

patch -p1 < dropbearsign.patch
patch -p1 < fix.patch
patch -p1 < fix2.patch

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --disable-syslog \
    --disable-shadow  \
    --disable-zlib \
    --disable-utmp \
    --disable-utmpx \
    --disable-wtmp \
    --disable-wtmpx \
    --disable-pututline \
    --disable-pututxline \
    --disable-openpty
   
make
make install

ln -sf dropbearmulti dbclient "$1/usr/bin/ssh"
