#!/bin/sh -e

export DESTDIR="$1"
export PATH="$1/usr/bin:$PATH"

# if you choose to use gnu-m4, we wont need to vendor gnu-m4
if kiss l gnu-m4; then

cd libtool

./configure \
	--prefix=/usr

make
make install

# if we rather use om4 from core, we need to vendor gnu-m4, as libtool doesnt
# build with om4.
else

cd m4/

./configure \
	--prefix=/usr 

make LDFLAGS="$LDFLAGS -static"
make install

cd ../libtool

./configure \
    --prefix=/usr

make
make install

# now remove gnu-m4 
rm -rf \
	"$1/usr/bin/m4" \
	"$1/usr/share/man/man1/m4.1" \
	"$1/usr/share/info/m4.info-2" \
	"$1/usr/share/info/m4.info-1" \
	"$1/usr/share/info/m4.info" 

fi
