#!/bin/sh -e

./configure \
    --without-debug \
    --prefix=/usr \

make 
make install

./configure \
    --without-debug \
    --prefix=/usr \
    --disable-shared \
    --enable-static

make LDFLAGS="$LDFLAGS --static"
make install
