#!/bin/sh -e

patch -p1 < 0001-wiphy-Remove-basename-use.patch

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus \
    --disable-shared \
    --enable-static

make LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -fPIE"
make DESTDIR="$1" install

cp -f iwd_passphrase "$1/usr/bin"

mkdir -p "$1/etc/rcsm/avail"
cp -f  eiwd.run "$1/etc/rcsm/avail/eiwd"
