#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus \
    --disable-shared \
    --enable-static

make LDFLAGS="$LDFLAGS --static"
make DESTDIR="$1" install

cp -f iwd_passphrase "$1/usr/bin"

mkdir -p "$1/etc/rcsm/avail"
cp -f  eiwd.run "$1/etc/rcsm/avail/eiwd"
