#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-doc \
    --disable-nls \
    --disable-shared \
    --disable-microlzma \
    --disable-lzip-decoder \
    --disable-xzdec \
    --disable-lzmadec \
    --disable-lzmainfo \
    --disable-lzma-links \
    --disable-scripts

make LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -fPIE"
make DESTDIR="$1" install
