#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-doc \
    --disable-nls \
    --disable-shared \
    --disable-microlzma

make LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -fPIE"
make DESTDIR="$1" install
