#!/bin/sh -e

# vendor in ncurses, because catgirl wont build with netbsd-curses
cd ncurses/

./configure \
    --prefix=/usr \
    --disable-rpath-hack \
    --without-ada \
    --without-tests \
    --without-debug \
    --without-cxx-binding \
    --without-manpages

make LDFLAGS="$LDFLAGS -static"
make install

cd ../catgirl

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man

make LDFLAGS="$LDFLAGS -static"
make install

# remove ncurses, as we no longer need it
cd ../ncurses
make uninstall

# some minor cleanup after ncurses
rm -rf \
    "$1/usr/lib/" \
    "$1/usr/include" \
    "$1/usr/share/pkgconfig"
