#!/bin/sh -e

export DESTDIR="$1"

# build will without it.
# have to look into how to statically link libmpdclient
sed '/libmpdclient:default_library=static/d' meson.build > _
mv -f _ meson.build

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    output

ninja -C output
muon -C output install
