#!/bin/sh -e

mkdir -p \
    "$1/usr/lib/firmware/amd-ucode" \
    "$1/usr/lib/firmware/amdgpu" \
    "$1/usr/lib/firmware/ath10k/QCA9377/hw1.0" \
    "$1/usr/lib/firmware/rtl_nic" 

cp \
    rtl_nic/rtl8411-2.fw \
    "$1/usr/lib/firmware/rtl_nic"

cp \
    ath10k/QCA9377/hw1.0/*.bin \
    "$1/usr/lib/firmware/ath10k/QCA9377/hw1.0"

cp \
    amdgpu/picasso* \
    "$1/usr/lib/firmware/amdgpu"

cp \
    amd-ucode/microcode_amd_fam17h.bin \
    "$1/usr/lib/firmware/amdp-ucode"

