#!/bin/sh -e

#export LDFLAGS="$LDFLAGS --static"
export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Ddocs=disabled \
    -Dexamples=disabled \
    -Ddefault_library=both \
    build

ninja -C build
muon -C build install

# copy missing header file
cp -f include/tinyalsa/attributes.h "$1/usr/include/tinyalsa"

# there seems to be a bug with muon which does not install some utils.
#cp -f \
#  build/utils/tinymix \
#  build/utils/tinycap \
#  build/utils/tinypcminfo \
#  "$1/usr/bin"
