#!/bin/sh -e

export LDFLAGS="$LDFLAGS --static"
export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Ddocs=disabled \
    -Dexamples=disabled \
    -Ddefault_library=static \
    build

ninja -C build
muon -C build install

# there seems to be a bug with muon which does not install some utils.
cp -f \
  build/utils/tinymix \
  build/utils/tinycap \
  build/utils/tinypcminfo \
  "$1/usr/bin"
