#!/bin/sh

make LDFLAGS="$LDFLAGS -static"
make  PREFIX=/usr install

# drop shared libs
rm -r \
	"$1/usr/lib/libterminfo.so" \
	"$1/usr/lib/libpanelw.so" \
	"$1/usr/lib/libpanel.so" \
	"$1/usr/lib/libtermcap.so" \
	"$1/usr/lib/libncursesw.so" \
	"$1/usr/lib/libncurses.so" \
	"$1/usr/lib/libmenuw.so" \
	"$1/usr/lib/libform.so" \
	"$1/usr/lib/libformw.so" \
	"$1/usr/lib/libmenu.so" \
	"$1/usr/lib/libcurses.so" 

#for libs in curses terminfo panel menu form; do
#    chmod 755 "$1/usr/lib/lib${libs}.so"
#done
