#!/bin/sh -e

CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr \
    --enable-silent-rules  \
    --disable-builtin-echo \
    --with-edit=editline \
    --disable-dependency-tracking

make
make install
