#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-privsep-user=ntpd \
    --with-cacert=/etc/ssl/cert.pem

make LDFLAGS="$LDFLAGS --static"
make install

#mkdir -p "$1/etc/sv/openntpd"
#cp -f ntpd.run "$1/etc/sv/openntpd/run"
#ln -sf /run/runit/supervise.openntpd "$1/etc/sv/openntpd/supervise"
