#!/bin/sh
cat <<EOF
OpenNTPD needs its own user and group for privilege separation.
Please create the needed users by using these commands in
succession:

  # addgroup -S ntpd
  # adduser -S -h /var/empty -G ntpd ntpd

Please also add the following lines to /etc/services:

ntp		123/tcp
ntp		123/udp

EOF
