#!/bin/sh -e

make CC="$CC $CFLAGS -static-pie -fPIE -fPIC $LDFLAGS" bzip2

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/lib" \
    "$1/usr/share/man/man1" \
    "$1/usr/include"

cp -f \
    bzip2 \
    bzdiff \
    bzgrep \
    bzmore \
    "$1/usr/bin"

cp -f libbz2.a "$1/usr/lib"

cp -f bzip2.1 "$1/usr/share/man/man1"
cp -f bzlib.h "$1/usr/include"

ln -sf bzip2 "$1/usr/bin/bunzip2"
ln -sf bzip2 "$1/usr/bin/bzcat"
