#!/bin/sh -e

# Setup docutils to generate manual pages.
{
    cd docutils

    python3 setup.py build
    python3 setup.py install \
        --root="$PWD/../dist"

    cd ../dist/usr/lib/python*/site-packages

    PYTHONPATH=$PWD:$(python -c "import sys;print(':'.join(sys.path))")

    cd -; cd ..
    export PATH=$PWD/dist/usr/bin:$PATH
    export PYTHONPATH
}

export LDFLAGS="$LDFLAGS -static"

meson \
    --prefix=/usr \
    -Dx11=enabled \
    -Dmanpage-build=enabled \
    -Degl=disabled \
    -Degl-x11=disabled \
    -Dgl=disabled \
    -Ddrm=disabled \
    -Dgbm=disabled \
    -Dalsa=disabled \
    -Dsndio=disabled \
    . build

# to avoid having to build only static libs for alot of stuff,
# we force the use of static libs instead
sed 's/\.so/\.a/g' build/build.ninja > _
mv -f _ build/build.ninja
sed 's/libatomic.a.1.2.0/libatomic.a/g' build/build.ninja > _
mv -f _ build/build.ninja

ninja -C build
ninja -C build install

# we probably dont need these
rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/icons"
