#!/bin/sh -e

# respawn is provided by ubase
sed 's/respawn//' Makefile > _
mv -f _ Makefile

sed 's/etc/\/lib\/init/' init.c > _
mv -f _ init.c

sed 's/rc/rc.boot/g' init.c > _
mv -f _ init.c

make LDFLAGS="$LDFLAGS -static"

chmod 755 shutdown

mkdir -p "$1/usr/bin"

cp -f init shutdown "$1/usr/bin"
