#!/bin/sh -e

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dtls_check=false \
    -Dpkcs11_tests=disabled \
    -Dvapi=disabled \
    -Dgssapi=disabled \
    -Dbrotli=disabled \
    -Dsysprof=disabled \
    . output

ninja -C output
ninja -C output install
