#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIE"
export LDFLAGS="$LDFLAGS -static-pie"

./configure \
    --prefix=/usr \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$1" install

ln -s flex "$1/usr/bin/lex"

rm -rf "$1/usr/share/doc"
