#!/bin/sh -e

export DESTDIR="$1"

#patch -p1 < sndio.patch

meson setup \
    -Dprefix=/usr \
    -Dgl=disabled \
    -Dtests=disabled \
    -Dtremor=disabled \
    -Dexamples=disabled \
    -Dcdparanoia=disabled \
    -Dintrospection=disabled \
    -Dalsa=enabled \
    output

ninja -C output
ninja -C output install
