#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < sndio.patch

meson \
    --prefix=/usr \
    -Dgl=disabled \
    -Dtests=disabled \
    -Dtremor=disabled \
    -Dexamples=disabled \
    -Dcdparanoia=disabled \
    -Dintrospection=disabled \
    -Dsndio=enabled \
    -Dalsa=disabled \
    . output

ninja -C output
ninja -C output install
