#!/bin/sh -e

# Avoid pkgconf
cat > config.mk <<EOF
PREFIX    = /usr
BINDIR    = $(PREFIX)/bin
MANPREFIX = ${PREFIX}/share/man

AR        = ar
CC        = cc
RANLIB    = ranlib
RM        = rm -f
YACC      = yacc

TLSLIB    = -ltls
BIN      += nc
MAN      += usr.bin/nc/nc.1
ZLIB      = -lz
LIBOBJ   += lib/libc/gen/fts.o
CFLAGS   += -DHAVE_LESS_T
EOF

make pax patch diff LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -fPIE"

# Bypass makefile to make sure everything is in order
chmod 755 diff patch pax

mkdir -p \
	"$1/usr/bin" \
	"$1/usr/share/man/man1"

cp -f pax diff patch        "$1/usr/bin"

cp -f usr.bin/diff/diff.1   "$1/usr/share/man/man1"
cp -f usr.bin/patch/patch.1 "$1/usr/share/man/man1"
cp -f bin/pax/pax.1         "$1/usr/share/man/man1"
cp -f bin/pax/tar.1         "$1/usr/share/man/man1"
cp -f bin/pax/cpio.1        "$1/usr/share/man/man1"

# symlink to tar and cpio
ln -s pax "$1/usr/bin/tar"
ln -s pax "$1/usr/bin/cpio"
