#!/bin/sh -e

CFLAGS_FOR_BUILD=-fPIC \
./configure \
    --prefix=/usr \
    --without-xmlto \
    --disable-specs 

make LDFLAGS="$LDFLAGS -lxcb -lXau"
make DESTDIR="$1" install

# Remove library documentation.
rm -rf "$1/usr/share/man/man3"
