#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dintel=disabled \
    -Dnouveau=disabled \
    -Damdgpu=disabled \
    -Dradeon=disabled \
    -Dvalgrind=disabled \
    -Ddefault_library=both \
    . build

ninja -C build
ninja -C build install
