#!/bin/sh -e

export XSERVERCFLAGS_CFLAGS="--static"
export XSERVERLIBS_LIBS="/usr/lib/*.a -lz -lfreetype -lpng16 -lharfbuzz"

./configure \
  --prefix=/usr \
  --with-fontdir=/usr/share/fonts \
  --disable-xdmcp \
  --disable-xdm-auth-1

make
make install

chmod u+s "$1/usr/bin/Xfbdev"

# not compatible
rm -rf "$1/usr/bin/Xvesa"

#install minimum requirement for bitmap fonts
mkdir -p "$1/usr/share/fonts/misc"
cp ./*.pcf.gz fonts.alias fonts.dir "$1/usr/share/fonts/misc"
