#!/bin/sh -e

export DESTDIR="$1"


# Don't build tests that fail due to `gnutls` not being built with `p11-kit`.
sed "/subdir('tls\/tests')/d" meson.build > _
mv -f _ meson.build

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dlocalstatedir=/var \
    -Dlibproxy=disabled \
    -Dopenssl=disabled \
    -Dgnutls=enabled \
    output

ninja -C output
muon -C output install
