#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests that fail due to `gnutls` not being built with `p11-kit`.
sed "/subdir('tests')/d" tls/meson.build > _
mv -f _ tls/meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dlibproxy=disabled \
    -Dopenssl=disabled \
    -Dgnutls=enabled \
    -Dgnome_proxy=disabled \
    . output

ninja -C output
ninja -C output install
