#!/bin/sh -e

patch -p1 < portability.patch

./configure \
    --prefix=/usr \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-lto

make LDFLAGS="$LDFLAGS -static"
make install
