#!/bin/sh -e

# fix typo in filename before we can unpack it
mv -f xfsprogs-6.1.0.tag.xz?no_extract xfsprogs-6.1.0.tar.xz
xz -dc xfsprogs-6.1.0.tar.xz | pax -r

cd xfsprogs-6.1.0

# Remove incorrect bash dependency.
sed 's/bash/sh/' install-sh > _
mv -f _ install-sh

# There seem to be a permission error, making this non-executable, which makes
# the build fail
chmod +x install-sh

# Explicitly include <signal.h> instead of implicit inclusion.
sed '1i#include <signal.h>' include/linux.h > _
mv -f _ include/linux.h

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --disable-gettext \
    --disable-shared \
    --disable-libicu \
    --with-pic=no

make
make \
    DIST_ROOT="$1" \
    PKG_ROOT_SBIN_DIR=/usr/bin \
    PKG_ROOT_LIB_DIR=/usr/lib \
    install 

# remove unneeded stuff
rm -rf \
    "$1/usr/lib" \
    "$1/usr/include" \
    "$1/usr/share/doc"
