#!/bin/sh -e

export LDFLAGS="$LDFLAGS --static"

# Remove incorrect bash dependency.
sed 's/bash/sh/' install-sh > _
mv -f _ install-sh

# Fix permissions 
chmod +x install-sh

# Explicitly include <signal.h> instead of implicit inclusion.
sed '1i#include <signal.h>' include/linux.h > _
mv -f _ include/linux.h

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --disable-gettext \
    --disable-shared \
    --disable-libicu \
    --with-pic=no

make
make \
    DIST_ROOT="$1" \
    PKG_ROOT_SBIN_DIR=/usr/bin \
    PKG_ROOT_LIB_DIR=/usr/lib \
    install 

# remove unneeded stuff
rm -rf \
    "$1/usr/lib" \
    "$1/usr/include" \
    "$1/usr/share/doc"
