#!/bin/sh -e

./configure \
	--enable-static

make

mkdir -p "$1/usr/bin/"
mkdir -p "$1/usr/share/man/man1"

cp om4 "$1/usr/bin/"
cp m4.1 "$1/usr/share/man/man1/om4.1"

# to provide an alternative to m4
ln -s om4 "$1/usr/bin/m4"
