#!/bin/sh -e

#make LDFLAGS="$LDFLAGS -static -lX11 -lXft -lxcb -lXrender -lfreetype \
#-lfontconfig -lpng -lXinerama -lz -lXext -lfontconfig -lexpat \
#-lXau"

make
make DESTDIR="$1" PREFIX=/usr install
