#!/bin/sh -e

make LDFLAGS="$LDFLAGS -static -lncursesw"

mkdir -p "$1/usr/bin/"
mkdir -p "$1/usr/share/man/man1"

cp dvtm "$1/usr/bin/"
cp dvtm-status "$1/usr/bin/"
cp dvtm.1 "$1/usr/share/man/man1"
